### ISSUE TITLE
Newton namespace prohibits from using regular float functions

### ISSUE THREAD

**Issue by daniel-jasinski** [jaredhoberock/newton#1] opened 2015-11-03 15:44 UTC
When compiling a very simple program:

```
#include <thrust/functional.h>
#include <newton/newton.hpp>

using namespace newton;

int main()
{
    float b = 7;
    b = abs(b);
    return 0;
}
```

I get an error:

./newton/detail/range/range_traits.hpp(44): error: name followed by "::" must be a class or namespace name
          detected during:
            instantiation of class "newton::detail::type_traits_detail::nested_iterator<Range> [with Range=float]" 
(67): here
            instantiation of class "newton::detail::type_traits_detail::range_mutable_iterator<Range> [with Range=float]" 
/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/detail/type_traits.h(419): here
            instantiation of class "thrust::detail::eval_if<false, Then, Else> [with Then=newton::detail::type_traits_detail::range_const_iterator<float>, Else=newton::detail::type_traits_detail::range_mutable_iterator<float>]" 
(198): here
            instantiation of class "newton::detail::range_iterator<Range> [with Range=float]" 
(210): here
            instantiation of class "newton::detail::range_value<Range> [with Range=float]" 
test.cu(11): here

/usr/include/c++/4.8/bits/stl_iterator_base_types.h(165): error: name followed by "::" must be a class or namespace name
          detected during:
            instantiation of class "std::iterator_traits<_Iterator> [with _Iterator=<error-type>]" 
/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/iterator/iterator_traits.h(44): here
            instantiation of class "thrust::iterator_traits<T> [with T=<error-type>]" 
/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/iterator/detail/iterator_traits.inl(32): here
            instantiation of class "thrust::iterator_value<Iterator> [with Iterator=<error-type>]" 
./newton/detail/range/range_traits.hpp(209): here
            instantiation of class "newton::detail::range_value<Range> [with Range=float]" 
test.cu(11): here

Is there a quick fix to this? I would like to use math functions without the newton:: prefix.

**Comment by jaredhoberock** [comment] 2015-11-03 19:16
Hi Daniel,
I don't think there is a quick way to fix this, other than to avoid `using namespace newton` if you wish to use C math functions.

**Comment by daniel-jasinski** [comment] 2015-11-03 19:26
OK, and what about a not so quick solution? It is important because I would like to use Newton in my own namespace with my custom set of functions and operators.

**Comment by jaredhoberock** [comment] 2015-11-03 19:32
You could try fully-qualifying your use of C math functions like `abs`:

```
b = std::abs(b);
```

Otherwise I think the Newton math functions need to be guarded with SFINAE to avoid trying to instantiate them with simple numeric types.

**Comment by daniel-jasinski** [comment] 2015-11-03 20:10
Fully-qualified names would be very problematic since I would like to use Newton in a large existing codebase.

**Comment by jaredhoberock** [comment] 2015-11-04 19:01
Problem seems to be that the `__NEWTON_DEFINE_UNARY_RANGE_FUNCTION` uses

```
typename detail::range_value<Range>::type
```

inside its use of `lazy_enable_if_range`. The problem is that when `Range` is a type that is not a `Range`, e.g. `float`, `range_value<float>::type` is undefined.

The fix would be to somehow lazily evaluate `range_value<Range>::type` when we are sure that `Range` really is a `Range` type.

**Comment by daniel-jasinski** [comment] 2015-11-04 21:03
What about creating an additional trait class that can be used to disable templates on specified types?

**Comment by jaredhoberock** [comment] 2015-11-07 19:28
Should be fixed now if you compile in c++11 mode.

```
$ cat test.cu
#include <thrust/functional.h>
#include <newton/newton.hpp>

using namespace newton;

int main()
{
    float b = 7;
    b = abs(b);
    return 0;
}
$ nvcc -std=c++11 -I. test.cu 
```

**Closed as completed** 2015-11-07 19:28 UTC
